name: imap_client
description: IMAP (version 4rev1) implementation to get emails from an external server
version: 0.2.8
homepage: https://github.com/michaelspiss/imap_client
author: Michael Spiss <michaelspiss.dev@mailbox.org>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  logging: ^0.11.4
  pedantic: ^1.9.0
  utf7: ^0.2.1

dev_dependencies:
  test: ^1.14.1
  mockito: ^4.1.1
